services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    networks:
      - depth-mlops
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    networks:
      - depth-mlops
    ports:
      - "9095:9095"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9095", "--list"]
      interval: 5s
      timeout: 10s
      retries: 10

  kafka-setup:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - depth-mlops
    restart: on-failure
    entrypoint: ["/bin/bash", "-c"]
    command: |
      "
      echo 'Ожидание готовности Kafka...'
      while ! kafka-topics --bootstrap-server kafka:9092 --list; do
        sleep 1
      done

      echo 'Создание топиков...'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic depth_requests --partitions 3 --replication-factor 1 --config retention.ms=604800000
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic depth_events   --partitions 3 --replication-factor 1 --config retention.ms=604800000

      echo 'Топики успешно созданы:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    networks:
      - depth-mlops
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  postgres:
    image: postgres:16
    networks:
      - depth-mlops
    environment:
      POSTGRES_DB: depthdb
      POSTGRES_USER: depth
      POSTGRES_PASSWORD: depth
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U depth -d depthdb"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build: ./services/ml_service
    networks:
      - depth-mlops
    environment:
      DATABASE_URL: "postgresql://depth:depth@postgres:5432/depthdb"
      KAFKA_BOOTSTRAP: "kafka:9092"
      KAFKA_TOPIC_REQUESTS: "depth_requests"
      KAFKA_TOPIC_EVENTS: "depth_events"
    depends_on:
      kafka:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models:ro

  worker:
    build: ./services/ml_service
    networks:
      - depth-mlops
    command: ["python", "-m", "app.worker"]
    environment:
      DATABASE_URL: "postgresql://depth:depth@postgres:5432/depthdb"
      KAFKA_BOOTSTRAP: "kafka:9092"
      KAFKA_TOPIC_REQUESTS: "depth_requests"
      KAFKA_TOPIC_EVENTS: "depth_events"
      MODEL_WEIGHTS_PATH: "/models/model.pt"
      DEVICE: "cpu"
    depends_on:
      kafka:
        condition: service_healthy
      kafka-setup:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    volumes:
      - ./models:/models:ro

  ui:
    build: ./services/ui
    networks:
      - depth-mlops
    environment:
      API_URL: "http://api:8000"
    depends_on:
      - api
    ports:
      - "8501:8501"

networks:
  depth-mlops:
    name: depth-mlops
    driver: bridge

volumes:
  pgdata:
